### ISSUE TITLE
The JSON string is invalid for CFPaymentsEntityMethod with oneOf schemas

### ISSUE THREAD

**Issue by kuldeepiitg** [cashfree/cashfree-pg-sdk-java#3]
I am trying to get payments for an order as follow:

```java
    @SneakyThrows
    public List<CFPaymentsEntity> getPaymentDetails(String orderId) {

        ApiResponse<List<CFPaymentsEntity>> payments = cfPaymentGatewayService.getAllPayments(cfConfig, CFHeaders.builder().build(), orderId);
        if (payments.getStatusCode() != 200) {
            throw PaymentServiceException.create(ResponseCode.PAYMENT_GATEWAY_ERROR);
        }

        return payments.getData();
    }
```

But failing with following error

```text
ERROR [2023-04-16 18:13:48,302] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: ef1d9d7910353068
! java.io.IOException: The JSON string is invalid for CFPaymentsEntityMethod with oneOf schemas: CFPaymentsEntityAppPayment, CFPaymentsEntityCardPayment, CFPaymentsEntityCardlessEMIPayment, CFPaymentsEntityNetbankingPayment, CFPaymentsEntityPaylaterPayment, CFPaymentsEntityUPIPayment. 0 class(es) match the result, expected 1. Detailed failure message for oneOf schemas: [Deserialization for CFPaymentsEntityAppPayment failed with `The field `others` in the JSON string is not defined in the `CFPaymentsEntityAppPayment` properties. JSON: {"others":{"card_number":"XXXXXXilure@gocash","card_country":"","card_network":null,"payment_mode":"UPI_CREDIT_CARD","bank_number":null,"upi_id":null,"bank_account":""}}`., Deserialization for CFPaymentsEntityCardPayment failed with `The field `others` in the JSON string is not defined in the `CFPaymentsEntityCardPayment` properties. JSON: {"others":{"card_number":"XXXXXXilure@gocash","card_country":"","card_network":null,"payment_mode":"UPI_CREDIT_CARD","bank_number":null,"upi_id":null,"bank_account":""}}`., Deserialization for CFPaymentsEntityCardlessEMIPayment failed with `The field `others` in the JSON string is not defined in the `CFPaymentsEntityCardlessEMIPayment` properties. JSON: {"others":{"card_number":"XXXXXXilure@gocash","card_country":"","card_network":null,"payment_mode":"UPI_CREDIT_CARD","bank_number":null,"upi_id":null,"bank_account":""}}`., Deserialization for CFPaymentsEntityNetbankingPayment failed with `The field `others` in the JSON string is not defined in the `CFPaymentsEntityNetbankingPayment` properties. JSON: {"others":{"card_number":"XXXXXXilure@gocash","card_country":"","card_network":null,"payment_mode":"UPI_CREDIT_CARD","bank_number":null,"upi_id":null,"bank_account":""}}`., Deserialization for CFPaymentsEntityPaylaterPayment failed with `The field `others` in the JSON string is not defined in the `CFPaymentsEntityPaylaterPayment` properties. JSON: {"others":{"card_number":"XXXXXXilure@gocash","card_country":"","card_network":null,"payment_mode":"UPI_CREDIT_CARD","bank_number":null,"upi_id":null,"bank_account":""}}`., Deserialization for CFPaymentsEntityUPIPayment failed with `The field `others` in the JSON string is not defined in the `CFPaymentsEntityUPIPayment` properties. JSON: {"others":{"card_number":"XXXXXXilure@gocash","card_country":"","card_network":null,"payment_mode":"UPI_CREDIT_CARD","bank_number":null,"upi_id":null,"bank_account":""}}`.]. JSON: {"others":{"card_number":"XXXXXXilure@gocash","card_country":"","card_network":null,"payment_mode":"UPI_CREDIT_CARD","bank_number":null,"upi_id":null,"bank_account":""}}
! at com.cashfree.pg.model.CFPaymentsEntityMethod.validateJsonObject(CFPaymentsEntityMethod.java:608)
! at com.cashfree.pg.model.CFPaymentsEntity.validateJsonObject(CFPaymentsEntity.java:817)
! at com.cashfree.pg.model.CFPaymentsEntity$CustomTypeAdapterFactory$1.read(CFPaymentsEntity.java:853)
! at com.cashfree.pg.model.CFPaymentsEntity$CustomTypeAdapterFactory$1.read(CFPaymentsEntity.java:842)
! at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:201)
! at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
! at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
! at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
! at com.google.gson.Gson.fromJson(Gson.java:1214)
! ... 80 common frames omitted
! Causing: com.google.gson.JsonSyntaxException: java.io.IOException: The JSON string is invalid for CFPaymentsEntityMethod with oneOf schemas: CFPaymentsEntityAppPayment, CFPaymentsEntityCardPayment, CFPaymentsEntityCardlessEMIPayment, CFPaymentsEntityNetbankingPayment, CFPaymentsEntityPaylaterPayment, CFPaymentsEntityUPIPayment. 0 class(es) match the result, expected 1. Detailed failure message for oneOf schemas: [Deserialization for CFPaymentsEntityAppPayment failed with `The field `others` in the JSON string is not defined in the `CFPaymentsEntityAppPayment` properties. JSON: {"others":{"card_number":"XXXXXXilure@gocash","card_country":"","card_network":null,"payment_mode":"UPI_CREDIT_CARD","bank_number":null,"upi_id":null,"bank_account":""}}`., Deserialization for CFPaymentsEntityCardPayment failed with `The field `others` in the JSON string is not defined in the `CFPaymentsEntityCardPayment` properties. JSON: {"others":{"card_number":"XXXXXXilure@gocash","card_country":"","card_network":null,"payment_mode":"UPI_CREDIT_CARD","bank_number":null,"upi_id":null,"bank_account":""}}`., Deserialization for CFPaymentsEntityCardlessEMIPayment failed with `The field `others` in the JSON string is not defined in the `CFPaymentsEntityCardlessEMIPayment` properties. JSON: {"others":{"card_number":"XXXXXXilure@gocash","card_country":"","card_network":null,"payment_mode":"UPI_CREDIT_CARD","bank_number":null,"upi_id":null,"bank_account":""}}`., Deserialization for CFPaymentsEntityNetbankingPayment failed with `The field `others` in the JSON string is not defined in the `CFPaymentsEntityNetbankingPayment` properties. JSON: {"others":{"card_number":"XXXXXXilure@gocash","card_country":"","card_network":null,"payment_mode":"UPI_CREDIT_CARD","bank_number":null,"upi_id":null,"bank_account":""}}`., Deserialization for CFPaymentsEntityPaylaterPayment failed with `The field `others` in the JSON string is not defined in the `CFPaymentsEntityPaylaterPayment` properties. JSON: {"others":{"card_number":"XXXXXXilure@gocash","card_country":"","card_network":null,"payment_mode":"UPI_CREDIT_CARD","bank_number":null,"upi_id":null,"bank_account":""}}`., Deserialization for CFPaymentsEntityUPIPayment failed with `The field `others` in the JSON string is not defined in the `CFPaymentsEntityUPIPayment` properties. JSON: {"others":{"card_number":"XXXXXXilure@gocash","card_country":"","card_network":null,"payment_mode":"UPI_CREDIT_CARD","bank_number":null,"upi_id":null,"bank_account":""}}`.]. JSON: {"others":{"card_number":"XXXXXXilure@gocash","card_country":"","card_network":null,"payment_mode":"UPI_CREDIT_CARD","bank_number":null,"upi_id":null,"bank_account":""}}
! at com.google.gson.Gson.fromJson(Gson.java:1229)
! at com.google.gson.Gson.fromJson(Gson.java:1124)
! at com.google.gson.Gson.fromJson(Gson.java:1034)
! at com.google.gson.Gson.fromJson(Gson.java:1001)
! at com.cashfree.pg.JSON.deserialize(JSON.java:277)
! at com.cashfree.pg.ApiClient.deserialize(ApiClient.java:887)
! at com.cashfree.pg.ApiClient.handleResponse(ApiClient.java:1102)
! at com.cashfree.pg.ApiClient.execute(ApiClient.java:1017)
! at com.cashfree.pg.api.PaymentsApi.getPaymentsfororderWithHttpInfo(PaymentsApi.java:619)
! at com.cashfree.pg.gatewayinterface.CFPaymentGatewayService.getAllPayments(CFPaymentGatewayService.java:137)
! at com.tarkshala.tavahot.ms.payments.clients.CashfreeClient.getPaymentDetails(CashfreeClient.java:129)
! at com.tarkshala.tavahot.ms.payments.services.CallbackService.updatePaymentState(CallbackService.java:31)
! at com.tarkshala.tavahot.ms.payments.services.CallbackService.handlePGPaymentNotification(CallbackService.java:26)
! at com.tarkshala.tavahot.ms.payments.resources.CallbackResource.handlePGPaymentNotification(CallbackResource.java:30)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
! at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.base/java.lang.reflect.Method.invoke(Method.java:568)
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
```

**Comment by prasunparijat-cashfree** [comment]
This error does not come anymore, hence closing the issue ticket.
